grails-app/domain/com/retouch/Coupon.groovy
package com.retouch

class Coupon {
    boolean active = true
    String name
    Integer discountPercent
    Integer daysValid = 30

    static constraints = {
        discountPercent(min:1,max:100)
    }
}

grails-app/controllers/com/retouch/CouponController.groovy
package com.retouch

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(["ROLE_ADMIN"])
class CouponController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Coupon.list(params), model: [couponInstanceCount: Coupon.count()]
    }

    def show(Coupon couponInstance) {
        respond couponInstance
    }

    def create() {
        respond new Coupon(params)
    }

    @Transactional
    def save(Coupon couponInstance) {
        if (couponInstance == null) {
            notFound()
            return
        }

        if (couponInstance.hasErrors()) {
            respond couponInstance.errors, view: 'create'
            return
        }

        couponInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'coupon.label', default: 'Coupon'), couponInstance.id])
                redirect couponInstance
            }
            '*' { respond couponInstance, [status: CREATED] }
        }
    }

    def edit(Coupon couponInstance) {
        respond couponInstance
    }

    @Transactional
    def update(Coupon couponInstance) {
        if (couponInstance == null) {
            notFound()
            return
        }

        if (couponInstance.hasErrors()) {
            respond couponInstance.errors, view: 'edit'
            return
        }

        couponInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Coupon.label', default: 'Coupon'), couponInstance.id])
                redirect couponInstance
            }
            '*' { respond couponInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Coupon couponInstance) {

        if (couponInstance == null) {
            notFound()
            return
        }

        couponInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Coupon.label', default: 'Coupon'), couponInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'coupon.label', default: 'Coupon'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/coupon/_form.gsp
<%@ page import="com.retouch.Coupon" %>



<div class="row">
<div class="form-group ${hasErrors(bean: couponInstance, field: 'discountPercent', 'error')} required">
    <div class="col-md-12">
	<label for="discountPercent" class="control-label">
		<g:message code="coupon.discountPercent.label" default="Discount Percent" />
		<span class="required-indicator">*</span>
	</label>

        <g:field name="discountPercent" type="number" min="1" max="100" value="${couponInstance.discountPercent}" required=""/>

    </div>

</div>
</div>

<div class="row">
<div class="form-group ${hasErrors(bean: couponInstance, field: 'active', 'error')} ">
    <div class="col-md-12">
	<label for="active" class="control-label">
		<g:message code="coupon.active.label" default="Active" />
		
	</label>

        <g:checkBox name="active" value="${couponInstance?.active}" />

    </div>

</div>
</div>

<div class="row">
<div class="form-group ${hasErrors(bean: couponInstance, field: 'daysValid', 'error')} required">
    <div class="col-md-12">
	<label for="daysValid" class="control-label">
		<g:message code="coupon.daysValid.label" default="Days Valid" />
		<span class="required-indicator">*</span>
	</label>

        <g:field name="daysValid" type="number" value="${couponInstance.daysValid}" required=""/>

    </div>

</div>
</div>

<div class="row">
<div class="form-group ${hasErrors(bean: couponInstance, field: 'name', 'error')} required">
    <div class="col-md-12">
	<label for="name" class="control-label">
		<g:message code="coupon.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>

        <g:textField name="name" required="" value="${couponInstance?.name}"/>

    </div>

</div>
</div>

grails-app/views/coupon/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'coupon.label', default: 'Coupon')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>
                        <g:message code="default.list.label" args="[entityName]" />
                    </h1>
                </div>
            </div>
        </div>
    </section>
    <div id="create-coupon" class="content scaffold-create container" role="main">
    %{--    <h1><g:message code="default.create.label" args="[entityName]" /></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>--}%
        <g:hasErrors bean="${couponInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${couponInstance}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <g:form url="[resource:couponInstance, action:'save']" >
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="mb-xs mt-xs mr-xs btn btn-sm btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
        </fieldset>
        </g:form>
    </div>
</div>
</body>
</html>

grails-app/views/coupon/edit.gsp
<%@ page import="com.retouch.Coupon" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'coupon.label', default: 'Coupon')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>
                        <g:message code="default.list.label" args="[entityName]" />
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <div id="edit-coupon" class="content scaffold-edit container" role="main">
        %{--<h1><g:message code="default.edit.label" args="[entityName]" /></h1>--}%
        %{-- <g:if test="${flash.message}">
             <div class="message" role="status">${flash.message}</div>
         </g:if>--}%
        <div class="panel">
            <g:hasErrors bean="${couponInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${couponInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>
            <g:form url="[resource:couponInstance, action:'update']" method="PUT" >
            <g:hiddenField name="version" value="${couponInstance?.version}" />
            <fieldset class="form">
                <g:render template="form"/>
            </fieldset>
            <fieldset class="buttons">
                <g:actionSubmit class="mb-xs mt-xs mr-xs btn btn-sm btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
            </fieldset>
            </g:form>
        </div>

    </div>
</div>
</body>
</html>

grails-app/views/coupon/index.gsp
<%@ page import="com.retouch.Coupon" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'coupon.label', default: 'Coupon')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

	<div role="main" class="main">

		<section class="page-top">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb">
							<li><a class="home" href="${createLink(uri: '/')}"><g:message
										code="default.home.label" /></a></li>
							<li><g:message code="default.list.label" args="[entityName]" /></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h1>
							<g:message code="default.list.label" args="[entityName]" />
						</h1>
					</div>
				</div>
			</div>
		</section>

		<div class="container">
			<div class="alert alert-info">Change Text</div>

			<div class="panel-body">
				<div class="table-responsive">
				%{--	<g:if test="${flash.message}">
						<div class="message" role="status">${flash.message}</div>
					</g:if>--}%
					<table
						class="table table-bordered table-striped table-condensed mb-none">
						<thead>
							<tr>
								
						<g:sortableColumn property="discountPercent" title="${message(code: 'coupon.discountPercent.label', default: 'Discount Percent')}" />
					
						<g:sortableColumn property="active" title="${message(code: 'coupon.active.label', default: 'Active')}" />
					
						<g:sortableColumn property="daysValid" title="${message(code: 'coupon.daysValid.label', default: 'Days Valid')}" />
					
						<g:sortableColumn property="name" title="${message(code: 'coupon.name.label', default: 'Name')}" />
					
							</tr>
						</thead>
						<tbody>
							<g:each in="${couponInstanceList}" status="i"
								var="couponInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
									
									<td><g:link action="show" id="${couponInstance.id}">${fieldValue(bean: couponInstance, field: "discountPercent")}</g:link></td>
								
									<td><g:formatBoolean boolean="${couponInstance.active}" /></td>
								
									<td>${fieldValue(bean: couponInstance, field: "daysValid")}</td>
								
									<td>${fieldValue(bean: couponInstance, field: "name")}</td>
								

								</tr>
							</g:each>
						</tbody>
					</table>
					<ul class="pagination">
						<retouch:paginate total="${couponInstanceCount ?: 0}" />
					</ul>

				</div>
			</div>
			</section>
		</div>
	</div>
</body>
</html>

grails-app/views/coupon/show.gsp
<%@ page import="com.retouch.Coupon" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'coupon.label', default: 'Coupon')}" />
    <title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>
                        <g:message code="default.list.label" args="[entityName]" />
                    </h1>
                </div>
            </div>
        </div>
    </section>


  <div id="show-coupon" class="content scaffold-show container" role="main">
        <ul class="property-list coupon">
            
            <g:if test="${couponInstance?.discountPercent}">
                <li class="fieldcontain">
                    <span id="discountPercent-label" class="property-label"><g:message code="coupon.discountPercent.label" default="Discount Percent" /></span>
                    
                    <span class="property-value" aria-labelledby="discountPercent-label"><g:fieldValue bean="${couponInstance}" field="discountPercent"/></span>
                    
                </li>
            </g:if>
            
            <g:if test="${couponInstance?.active}">
                <li class="fieldcontain">
                    <span id="active-label" class="property-label"><g:message code="coupon.active.label" default="Active" /></span>
                    
                    <span class="property-value" aria-labelledby="active-label"><g:formatBoolean boolean="${couponInstance?.active}" /></span>
                    
                </li>
            </g:if>
            
            <g:if test="${couponInstance?.daysValid}">
                <li class="fieldcontain">
                    <span id="daysValid-label" class="property-label"><g:message code="coupon.daysValid.label" default="Days Valid" /></span>
                    
                    <span class="property-value" aria-labelledby="daysValid-label"><g:fieldValue bean="${couponInstance}" field="daysValid"/></span>
                    
                </li>
            </g:if>
            
            <g:if test="${couponInstance?.name}">
                <li class="fieldcontain">
                    <span id="name-label" class="property-label"><g:message code="coupon.name.label" default="Name" /></span>
                    
                    <span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${couponInstance}" field="name"/></span>
                    
                </li>
            </g:if>
            
        </ul>
        <g:form url="[resource:couponInstance, action:'delete']" method="DELETE">
            <fieldset class="buttons">
                <g:link class="mb-xs mt-xs mr-xs btn btn-sm btn-default" action="edit" resource="${couponInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                <g:actionSubmit class="mb-xs mt-xs mr-xs btn btn-sm btn-primary" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </fieldset>
        </g:form>
    </div>
</div>
</body>
</html>