grails-app/domain/com/retouch/SiteParams.groovy
package com.retouch

class SiteParams {
    String parameterName
    String parameterValue

    static constraints = {
        parameterName(unique: true, nullable:false,blank:false)
        parameterValue(nullable:false,blank:false, maxSize: 500)
    }
}

grails-app/controllers/com/retouch/SiteParamsController.groovy
package com.retouch

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(["ROLE_ADMIN"])
class SiteParamsController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 20, 100)
        respond SiteParams.list(params), model: [siteParamsInstanceCount: SiteParams.count()]
    }

    def show(SiteParams siteParamsInstance) {
        respond siteParamsInstance
    }

    def create() {
        respond new SiteParams(params)
    }

    @Transactional
    def save(SiteParams siteParamsInstance) {
        if (siteParamsInstance == null) {
            notFound()
            return
        }

        if (siteParamsInstance.hasErrors()) {
            respond siteParamsInstance.errors, view: 'create'
            return
        }

        siteParamsInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'siteParams.label', default: 'SiteParams'), siteParamsInstance.id])
                redirect siteParamsInstance
            }
            '*' { respond siteParamsInstance, [status: CREATED] }
        }
    }

    def edit(SiteParams siteParamsInstance) {
        respond siteParamsInstance
    }

    @Transactional
    def update(SiteParams siteParamsInstance) {
        if (siteParamsInstance == null) {
            notFound()
            return
        }

        if (siteParamsInstance.hasErrors()) {
            respond siteParamsInstance.errors, view: 'edit'
            return
        }

        siteParamsInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'SiteParams.label', default: 'SiteParams'), siteParamsInstance.id])
                redirect siteParamsInstance
            }
            '*' { respond siteParamsInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(SiteParams siteParamsInstance) {

        if (siteParamsInstance == null) {
            notFound()
            return
        }

        siteParamsInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'SiteParams.label', default: 'SiteParams'), siteParamsInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'siteParams.label', default: 'SiteParams'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/siteParams/_form.gsp
<%@ page import="com.retouch.SiteParams" %>



<div class="row">
<div class="form-group ${hasErrors(bean: siteParamsInstance, field: 'parameterName', 'error')} required">
    <div class="col-md-12">
	<label for="parameterName" class="control-label">
		<g:message code="siteParams.parameterName.label" default="Parameter Name" />
		<span class="required-indicator">*</span>
	</label>

        <g:textField name="parameterName" required="" value="${siteParamsInstance?.parameterName}"/>

    </div>

</div>
</div>

<div class="row">
<div class="form-group ${hasErrors(bean: siteParamsInstance, field: 'parameterValue', 'error')} required">
    <div class="col-md-12">
	<label for="parameterValue" class="control-label">
		<g:message code="siteParams.parameterValue.label" default="Parameter Value" />
		<span class="required-indicator">*</span>
	</label>

        <g:textField name="parameterValue" required="" value="${siteParamsInstance?.parameterValue}"/>

    </div>

</div>
</div>

grails-app/views/siteParams/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'siteParams.label', default: 'SiteParams')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <div id="create-siteParams" class="content scaffold-create container" role="main">
        <g:hasErrors bean="${siteParamsInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${siteParamsInstance}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <g:form url="[resource:siteParamsInstance, action:'save']" >
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="mb-xs mt-xs mr-xs btn btn-sm btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
        </fieldset>
        </g:form>
    </div>
</div>
</body>
</html>

grails-app/views/siteParams/edit.gsp
<%@ page import="com.retouch.SiteParams" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'siteParams.label', default: 'SiteParams')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div id="edit-siteParams" class="content scaffold-edit container" role="main">
        <div class="panel">
            <g:hasErrors bean="${siteParamsInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${siteParamsInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>
            <g:form url="[resource:siteParamsInstance, action:'update']" method="PUT" >
            <g:hiddenField name="version" value="${siteParamsInstance?.version}" />
            <fieldset class="form">
                <g:render template="form"/>
            </fieldset>
            <fieldset class="buttons">
                <g:actionSubmit class="mb-xs mt-xs mr-xs btn btn-sm btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
            </fieldset>
            </g:form>
        </div>

    </div>
</div>
</body>
</html>

grails-app/views/siteParams/index.gsp
<%@ page import="com.retouch.SiteParams" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'siteParams.label', default: 'SiteParams')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

	<div role="main" class="main">

		<section class="page-top">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb">
                            <li><a class="home" href="${createLink(uri: '/')}"><g:message
                                    code="default.home.label"/></a></li>
                            <li><g:message code="default.list.label" args="[entityName]"/></li>
                            <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                                                  args="[entityName]"/></g:link></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

		<div class="container">

			<div class="panel-body">
				<div class="table-responsive">
					<table
						class="table table-bordered table-striped table-condensed mb-none">
						<thead>
							<tr>
								
						<g:sortableColumn property="parameterName" title="${message(code: 'siteParams.parameterName.label', default: 'Parameter Name')}" />
					
						<g:sortableColumn property="parameterValue" title="${message(code: 'siteParams.parameterValue.label', default: 'Parameter Value')}" />
					
							</tr>
						</thead>
						<tbody>
							<g:each in="${siteParamsInstanceList}" status="i"
								var="siteParamsInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
									
									<td><g:link action="show" id="${siteParamsInstance.id}">${fieldValue(bean: siteParamsInstance, field: "parameterName")}</g:link></td>
								
									<td>${fieldValue(bean: siteParamsInstance, field: "parameterValue")}</td>
								

								</tr>
							</g:each>
						</tbody>
					</table>
					<ul class="pagination">
						<retouch:paginate total="${siteParamsInstanceCount ?: 0}" />
					</ul>

				</div>
			</div>
			</section>
		</div>
	</div>
</body>
</html>

grails-app/views/siteParams/show.gsp
<%@ page import="com.retouch.SiteParams" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'siteParams.label', default: 'SiteParams')}" />
    <title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>


  <div id="show-siteParams" class="content scaffold-show container" role="main">
        <ul class="property-list siteParams">
            
            <g:if test="${siteParamsInstance?.parameterName}">
                <li class="fieldcontain">
                    <span id="parameterName-label" class="property-label"><g:message code="siteParams.parameterName.label" default="Parameter Name" /></span>
                    
                    <span class="property-value" aria-labelledby="parameterName-label"><g:fieldValue bean="${siteParamsInstance}" field="parameterName"/></span>
                    
                </li>
            </g:if>
            
            <g:if test="${siteParamsInstance?.parameterValue}">
                <li class="fieldcontain">
                    <span id="parameterValue-label" class="property-label"><g:message code="siteParams.parameterValue.label" default="Parameter Value" /></span>
                    
                    <span class="property-value" aria-labelledby="parameterValue-label"><g:fieldValue bean="${siteParamsInstance}" field="parameterValue"/></span>
                    
                </li>
            </g:if>
            
        </ul>
        <g:form url="[resource:siteParamsInstance, action:'delete']" method="DELETE">
            <fieldset class="buttons">
                <g:link class="mb-xs mt-xs mr-xs btn btn-sm btn-default" action="edit" resource="${siteParamsInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                <g:actionSubmit class="mb-xs mt-xs mr-xs btn btn-sm btn-primary" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </fieldset>
        </g:form>
    </div>
</div>
</body>
</html>