grails-app/domain/com/retouch/User.groovy
package com.retouch

class User {

	transient springSecurityService

	String username
	String password
	String email
	String firstname
	String lastname
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
    String paypalAccount

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
		email blank:false, email:true
		firstname blank:false
		lastname blank:false
        paypalAccount nullable:true, blank:true
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

    def beforeValidate(){
        if(!username || username==""){
            username = email
        }
    }

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}

    String toString(){
        return username
    }

    public String getFirstname(){
        return firstname
    }

    public String getLastname(){
        return lastname
    }
}

grails-app/controllers/com/retouch/UserController.groovy
package com.retouch



import static org.springframework.http.HttpStatus.*

import javax.swing.GroupLayout.Spring;

import com.mysql.jdbc.AuthenticationPlugin;
import com.sun.org.apache.xerces.internal.parsers.SecurityConfiguration;

import grails.plugin.springsecurity.SpringSecurityService;
import grails.plugin.springsecurity.SpringSecurityUtils;

import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserController {

	def springSecurityService

	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def index(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		respond User.list(params), model:[userInstanceCount: User.count()]
	}

	def show(User userInstance){

		if(SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')){
			respond userInstance ,model:[userProjects: Project.findAllByClient(userInstance)]
		} else {
			respond springSecurityService.getCurrentUser() , model:[userProjects: Project.findAllByClient(springSecurityService.getCurrentUser())]
		}
	}

	def create() {
		respond new User(params)
		respond new Role(params.role)
	}

	@Transactional
	def save(User userInstance) {

		def userRole = Role.findByAuthority(params.role)

		if (userInstance == null) {
			notFound()
			return
		}

		if (userInstance.hasErrors()) {
			respond userInstance.errors, view:'create'
			return
		}
		try{
			userInstance.save flush:true
			UserRole.create userInstance, userRole, true
		}
		catch (Exception e) {
			flash.message = 'Problem Creating User.'
		}

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [
					message(code: 'user.label', default: 'User'),
					userInstance.id
				])
				redirect userInstance
			}
			'*' { respond userInstance, [status: CREATED] }
		}
	}

	def edit(User userInstance) {
		if(SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')){
			respond userInstance
		} else {
			respond springSecurityService.getCurrentUser()
		}
	}

	@Transactional
	def update(User userInstance) {

        if(SpringSecurityUtils.ifNotGranted('ROLE_ADMIN')){
            if(springSecurityService.getCurrentUser() != userInstance){
                notFound()
                return
            }
        }

		def userRole = Role.findById(params.role)

		if (userInstance == null) {
			notFound()
			return
		}

		if (userInstance.hasErrors()) {
			respond userInstance.errors, view:'edit'
			return
		}

		def deleteRole = UserRole.findByUser(userInstance)
        if(deleteRole && SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')){
            deleteRole.delete flush:true
        }

		userInstance.save flush:true

        if(SpringSecurityUtils.ifAllGranted('ROLE_ADMIN')){
            UserRole.create userInstance, userRole, true
        }

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [
					message(code: 'User.label', default: 'User'),
					userInstance.id
				])
				redirect action:'edit',id:userInstance.id
			}
			'*'{ respond userInstance, [status: OK] }
		}
	}

	@Transactional
	def delete(User userInstance) {

		if (userInstance == null) {
			notFound()
			return
		}

		userInstance.delete flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.deleted.message', args: [
					message(code: 'User.label', default: 'User'),
					userInstance.id
				])
				redirect action:"index", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}

	protected void notFound() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [
					message(code: 'user.label', default: 'User'),
					params.id
				])
				redirect action: "index", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/user/_formcreate.gsp
<%@ page import="com.retouch.User" %>
<%@ page import="com.retouch.Role"%>

<div class="container">
    <div class="row show-grid">
        <div class="col-md-3">
            <section>
                <div class="row fontawesome-icon-list">
                    <div class="col-md-12 col-sm-12">
                        <i class="fa fa-user"></i>
                        Enter Personal Information
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <i class="fa fa-unlock-alt"></i>
                        Select Access Control
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <i class="fa fa-key"></i>
                        Choose Password
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <i class="fa fa-thumbs-up"></i>
                        You are done!!!
                    </div>
                    <hr class="tall" />
                </div>
            </section>
        </div>
        <div class="col-md-8">
            <fieldset>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="firstname">First
                    Name</label>
                    <div class="col-md-8">
                        <g:textField name="firstname" id="firstname" class="form-control"
                                     required="" value="${userInstance?.firstname}" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="lastname">Last
                    Name</label>
                    <div class="col-md-8">
                        <g:textField name="lastname" id="lastname" class="form-control"
                                     required="" value="${userInstance?.lastname}" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="username">User
                    Name</label>
                    <div class="col-md-8">
                        <g:textField name="username" class="form-control" id="username"
                                     required="" value="${userInstance?.username}" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="email">Email</label>
                    <div class="col-md-8">
                        <g:field type="email" name="email" class="form-control" id="email"
                                 required="" value="${userInstance?.email}" />
                    </div>
                </div>
            </fieldset>
            <sec:ifAnyGranted roles="ROLE_ADMIN">
                <hr class="dotted tall">
                <h4 class="mb-xlg">Access Control</h4>
                <fieldset>
                    <div class="form-group">
                        <label class="col-xs-5 control-label mt-xs pt-none">User
                        Role</label>
                        <div class="col-md-5">
                            <div class="">
                                <g:select class="form-control populate" name="role" from="${Role.list()}"
                                          value="${userInstance.id ? userInstance?.authorities.iterator().next() : ""}" />
                                <label for="enabled"></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-5 control-label mt-xs pt-none">Enabled</label>
                        <div class="col-md-5">
                            <div class="checkbox-custom checkbox-default checkbox-inline mt-xs">
                                <g:checkBox name="enabled" id="enabled"
                                            value="${userInstance?.enabled}" />
                                <label for="enabled"></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-5 control-label mt-xs pt-none">Password
                        Expired</label>
                        <div class="col-md-5">
                            <div class="checkbox-custom checkbox-default checkbox-inline mt-xs">
                                <g:checkBox name="passwordExpired" id="passwordExpired"
                                            value="${userInstance?.passwordExpired}" />
                                <label for="passwordExpired"></label>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </sec:ifAnyGranted>
            <hr class="dotted tall">
            <h4 class="mb-xlg">Enter Password</h4>
            <fieldset class="mb-xl">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="password">
                        Password</label>
                    <div class="col-md-8">
                        <g:passwordField name="password" id="password" class="form-control"
                                         required="" value="${userInstance?.password}" />
                    </div>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-default">Reset</button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>

grails-app/views/user/_formedit.gsp
<%@ page import="com.retouch.User" %>
<%@ page import="com.retouch.Role" %>

<div class="container">
    <div class="row show-grid">
        <div class="col-md-3">
            <section>

                <div class="row fontawesome-icon-list">

                    <div class="col-md-12 col-sm-12">
                        <i class="fa fa-user"></i>
                            <g:fieldValue bean="${userInstance}" field="username"/>
                    </div>

                    <div class="col-md-12 col-sm-12">
                        <i class="fa fa-smile-o"></i>
                        <g:fieldValue bean="${userInstance}" field="firstname"/>
                        <g:fieldValue bean="${userInstance}" field="lastname"/>
                    </div>

                    <sec:ifAllGranted roles="ROLE_ADMIN">
                        <div class="col-md-12 col-sm-12">
                            <i class="fa fa-thumbs-up"></i>
                            <g:each in="${userInstance.authorities}" status="j" var="roleInstance">
                                <span class="tag label btn-danger">
                                    ${roleInstance}
                                </span>
                            </g:each>
                        </div>
                    </sec:ifAllGranted>
                    <hr class="tall"/>
                </div>
            </section>
        </div>

        <div class="col-md-8">
            <fieldset>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="firstname">First
                    Name</label>

                    <div class="col-md-8">
                        <g:textField name="firstname" id="firstname" class="form-control"
                                     required="" value="${userInstance?.firstname}"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label" for="lastname">Last
                    Name</label>

                    <div class="col-md-8">
                        <g:textField name="lastname" id="lastname" class="form-control"
                                     required="" value="${userInstance?.lastname}"/>
                    </div>
                </div>

            </fieldset>
            <sec:ifAnyGranted roles="ROLE_ADMIN">
                <hr class="dotted tall">
                <h4 class="mb-xlg">Access Control</h4>
                <fieldset>
                    <div class="form-group">
                        <label class="col-xs-5 control-label mt-xs pt-none">User
                        Role</label>

                        <g:each in="${userInstance?.authorities?.id}" status="i" var="authority">
                            <g:set var="authority" value="${authority}"></g:set>
                        </g:each>

                        <div class="col-md-5">
                            <div class="">
                                <g:select class="form-control populate" id="user" name="role" from="${Role.list()}"
                                          optionKey="id" value="${authority}"/>
                                <label for="enabled"></label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-5 control-label mt-xs pt-none">Enabled</label>

                        <div class="col-md-5">
                            <div class="checkbox-custom checkbox-default checkbox-inline mt-xs">
                                <g:checkBox name="enabled" id="enabled"
                                            value="${userInstance?.enabled}"/>
                                <label for="enabled"></label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-5 control-label mt-xs pt-none">Password
                        Expired</label>

                        <div class="col-md-5">
                            <div class="checkbox-custom checkbox-default checkbox-inline mt-xs">
                                <g:checkBox name="passwordExpired" id="passwordExpired"
                                            value="${userInstance?.passwordExpired}"/>
                                <label for="passwordExpired"></label>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </sec:ifAnyGranted>
            <br>
            <fieldset class="mb-xl">
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-default">Reset</button>
                    </div>
                </div>
            </div>
            </fieldset>
          %{--  <h4 class="mb-xlg">Enter Password</h4>
            <fieldset class="mb-xl">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="password">
                        Password</label>

                    <div class="col-md-8">
                        <g:passwordField name="password" id="password" class="form-control"
                                         required="" value="${userInstance?.password}"/>
                    </div>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-default">Reset</button>
                        </div>
                    </div>
                </div>
            </fieldset>--}%
        </div>
    </div>
</div>

grails-app/views/user/_formpassword.gsp
<%@ page import="com.retouch.User" %>
<%@ page import="com.retouch.Role" %>

<div class="container">
    <div class="row show-grid">
        <div class="col-md-3">

        </div>

        <div class="col-md-8">


            <hr class="dotted tall">
            <h4 class="mb-xlg">Change Password</h4>
            <fieldset class="mb-xl">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="password">
                        Password</label>

                    <div class="col-md-8">
                        <g:passwordField name="password" id="password" class="form-control"
                                         required="" value="" />
                        <g:each in="${userInstance?.authorities?.id}" status="i" var="authority">
                            <input id="role" name="role" value="${authority}" type="hidden"/>
                        </g:each>
                    </div>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Change</button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>

grails-app/views/user/_paypalform.gsp
<%@ page import="com.retouch.User" %>
<%@ page import="com.retouch.Role" %>

<div class="container">
    <div class="row show-grid">
        <div class="col-md-3">

        </div>

        <div class="col-md-8">


            <hr class="dotted tall">
            <h4 class="mb-xlg">Payment Account</h4>
            <fieldset class="mb-xl">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="paypalemail">
                        Paypal ID</label>

                    <div class="col-md-8">
                        <g:textField name="paypalAccount" id="paypalemail" class="form-control"   required="" value="${userInstance?.paypalAccount}" />
                    </div>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>

grails-app/views/user/create.gsp
<%@ page import="com.retouch.User"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'user.label', default: 'User')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

	<div role="main" class="main">

		<section class="page-top">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb">
							<li><a href="${createLink(uri:'/') }">Home</a></li>
							<li class="active"><a
								href="${createLink(uri:'/user') }"><g:message
										code="default.list.label" args="[entityName]" /></a></li>
                            <li><g:message code="default.create.label" args="[entityName]" /></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

		<div class="container">
			<g:if test="${flash.message}">
				<div class="message" role="status">
					${flash.message}
				</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
				<div class="alert alert-info">
					<ul role="alert">
						<g:eachError bean="${userInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</div>
			</g:hasErrors>


			<div class="panel-body">
					<g:if test="${flash.message}">
						<div class="message" role="status">
							${flash.message}
						</div>
					</g:if>
					<g:form url="[resource:userInstance, action:'save']"
						class="form-horizontal">
						<fieldset class="form">
							<g:render template="formcreate" />
						</fieldset>
					</g:form>
			</div>
			</section>
		</div>
	</div>
</body>
</html>

grails-app/views/user/edit.gsp
<%@ page import="com.retouch.User"%>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName"
           value="${message(code: 'user.label', default: 'User')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">
    <section class="page-top">
        <div class="container">
            <div class="row">
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <div class="col-md-12">
                        <ul class="breadcrumb">
                            <li class="active"><a href="${createLink(uri:'/user') }"><g:message
                                    code="default.list.label" args="[entityName]" /></a></li>
                            <li class="active"><a
                                    href="${createLink(uri:'/user/create') }"><g:message
                                        code="default.create.label" args="[entityName]" /></a></li>
                            <li class="active"><g:link class="edit" action="show" resource="${userInstance}">
                                <g:message code="default.show.label" args="[entityName]" /></g:link></li>
                        </ul>
                    </div>
                </sec:ifAnyGranted>
                <sec:ifAnyGranted roles="ROLE_RETOUCHER, ROLE_USER">
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="breadcrumb">
                                <li><a class="home" href="${createLink(uri: '/')}"><g:message
                                        code="default.home.label" /></a></li>
                                <li>My Profile</li>
                            </ul>
                        </div>
                    </div>
                </sec:ifAnyGranted>
            </div>
        </div>
    </section>

    <div class="container">
        <div class="nav" role="navigation"></div>
        %{--	<g:if test="${flash.message}">
                <div class="message" role="status">
                    ${flash.message}
                </div>
            </g:if>
            <g:hasErrors bean="${userInstance}">
                <div class="alert alert-info">
                    <ul role="alert">
                        <g:eachError bean="${userInstance}" var="error">
                            <li
                                <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                    error="${error}" /></li>
                        </g:eachError>
                    </ul>
                </div>
            </g:hasErrors>--}%

        <div class="panel-body">

            <g:form url="[resource:userInstance, action:'update']" method="PUT" class="form-horizontal">
                <g:hiddenField name="version" value="${userInstance?.version}" />
                <fieldset class="form">
                    <g:render template="formedit" />
                </fieldset>
            </g:form>
            <sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_RETOUCHER">
                <g:form url="[resource:userInstance, action:'update']" method="PUT" class="form-horizontal">
                    <g:hiddenField name="version" value="${userInstance?.version}" />
                    <fieldset class="form">
                        <g:render template="paypalform" />
                    </fieldset>
                </g:form>

            </sec:ifAnyGranted>

            <g:form url="[resource:userInstance, action:'update']" method="PUT" class="form-horizontal">
                <g:hiddenField name="version" value="${userInstance?.version}" />
                <fieldset class="form">
                    <g:render template="formpassword" />
                </fieldset>
            </g:form>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="com.retouch.User"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'user.label', default: 'User')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

	<div role="main" class="main">

		<section class="page-top">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb">
							<li><a href="${createLink(uri:'/') }">Home</a></li>
							<li class="active"><a
								href="${createLink(uri:'/user/create') }"><g:message
										code="default.create.label" args="[entityName]" /></a></li>
                            <li><g:message code="default.list.label" args="[entityName]" /></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

		<div class="container">

			<div class="panel-body">
				<div class="table-responsive">
					<g:if test="${flash.message}">
						<div class="alert alert-info" role="status">
							${flash.message}
						</div>
					</g:if>

					<div class="col-md-12">
						<table class="table table-striped">
							<thead>
								<tr>

									<g:sortableColumn property="firstname"
										title="${message(code: 'user.fullname.label', default: 'Name')}" />

									<g:sortableColumn property="username"
										title="${message(code: 'user.username.label', default: 'Username')}" />

                                    <th>Role</th>

									<g:sortableColumn property="accountExpired"
										title="${message(code: 'user.accountExpired.label', default: 'Account Enabled')}" />

								</tr>
							</thead>
							<tbody>
								<g:each in="${userInstanceList}" status="i" var="userInstance">
									<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

										<td><g:link action="show" id="${userInstance.id}">
												${fieldValue(bean: userInstance, field: "firstname")}
												${fieldValue(bean: userInstance, field: "lastname")}
											</g:link></td>

										<td>
											${fieldValue(bean: userInstance, field: "username")}
										</td>

                                        <td>
                                            <g:each in="${userInstance.authorities}" status="j" var="roleInstance">
                                                <span class="tag label btn-danger
                                                <g:if test="${roleInstance == 'ROLE_ADMIN'}">btn-danger</g:if>
                                                <g:if test="${roleInstance == 'ROLE_USER'}">btn-warning</g:if>
                                                <g:if test="${roleInstance == 'ROLE_RETOUCHER'}">btn-info</g:if> ">
                                                    ${roleInstance}
                                                </span>
                                            </g:each>

                                        </td>

                                        <td><span class="tag label
                                            <g:if test="${userInstance.enabled}">btn-primary</g:if>
                                            <g:else>btn-danger</g:else>">
                                            <g:formatBoolean boolean="${userInstance.enabled}" />
                                        </span></td>


									</tr>
								</g:each>
							</tbody>
						</table>
						<ul class="pagination">
							<retouch:paginate total="${userInstanceCount ?: 0}" />
						</ul>

					</div>
				</div>

			</div>
		</div>
	</div>
</body>
</html>