grails-app/domain/com/retouch/Project.groovy
package com.retouch

class Project {
    User assignedTo
    User client
    String note
    Date createdDate
    Date lastUpdated
    String status
    String projectId

    static hasOne = [task:Task]

    static constraints = {
        status(nullable: false,blank:false,inList: ["New","Complete","Paid","In Progress","In Review"])
        assignedTo(nullable:true,blank:true)
        note(nullable:true,blank:true, maxSize: 2000)
        client(nullable:false,blank:false)
        projectId(nullable: false,blank: false,unique: true)
    }

    def beforeUpdate() {
        lastUpdated = new Date()
    }

    def beforeValidate() {
        if (id == null) {
            createdDate = new Date()
            lastUpdated = new Date()
            status = "New"
        }
    }

    def static generateProjectId(){
        return (new Date()).time.toString()
    }

    String toString(){
        return projectId
    }


}

grails-app/domain/com/retouch/Task.groovy
package com.retouch
import org.grails.paypal.Payment

class Task {
    ReImage finalImage
    ReImage originalImage
    Payment payment

    static hasMany = [tags:ImageTag,techniques:Technique, comments:Comment]
    static belongsTo = [project:Project]


    static constraints = {
        finalImage(nullable:true,blank:true)
        payment(nullable: true, blank:true)
    }
}

grails-app/controllers/com/retouch/TaskController.groovy
package com.retouch

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(["ROLE_RETOUCHER","ROLE_ADMIN"])
class TaskController {

    def springSecurityService
    def myImageService
    def taskService
    def mailService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(["ROLE_RETOUCHER"])
    @Transactional
    def claimTask(Project projectInstance){
        if(projectInstance && !projectInstance.assignedTo){
            projectInstance.assignedTo  = (User)springSecurityService.getCurrentUser()
            projectInstance.status  = "In Progress"
            if(projectInstance.save(flush: true)){
                flash.message = "Task has been successfully claimed"
                redirect(action: "show",id:projectInstance.id )
                return
            }else{
                println "WARNING: Failed to change project status to In Progress"
            }
        }
        flash.message = "Claim Failed! Someone else must have claimed the task before you."
        redirect(action: "myTasks")
    }

    @Secured(["ROLE_RETOUCHER"])
    @Transactional
    def upload(Project projectInstance){
        def imageFile
        if(params.reimage){
            imageFile = request.getFile('reimage')
        }

        if(imageFile && !imageFile.empty) {
            def fileName = myImageService.saveImagePackage( imageFile )
            def image = new ReImage(imagePath: fileName)
            def imageToDelete = null
            if(projectInstance.task.finalImage){
                imageToDelete = ReImage.get(projectInstance.task.finalImage.id)
                projectInstance.task.finalImage = null


            }
            projectInstance.task.finalImage = image
            projectInstance.status = "In Review"


            def proj
            try{
                projectInstance.task.save(flush: true)
                proj =  projectInstance.save(flush: true)
                //Notify the Client

                mailService.sendMail {
                    to projectInstance.client.email
                    subject "Retouch Complete"
                    html "Your image retouch has been completed. " //TODO add detailed email
                }

            }
            catch(e){
                println e

            }
            if (proj) {
                imageToDelete?.save(flush:true)
                imageToDelete?.delete(flush:true)
                flash.message = "Image Uploaded"
            } else {
                // myImageService.deleteImagePackage(image)
                println projectInstance.errors
                flash.message = "Upload Failed!!! Please try again"
            }
        }else{
            flash.message = "Please select an image"
        }
        redirect(action: "show",id: projectInstance.id)
    }


    @Transactional
    def addTask(){

    }

    @Secured(["ROLE_RETOUCHER"])
    def myTasks(Integer max){
        println "My tassks"
       // taskService.notifyRetouchers(Task.get(1))
        params.max = Math.min(max ?: 10, 100)
        if(!params.sort){
            params.sort = "id"
            params.order = "desc"
        }
        respond Project.findAllByAssignedTo(springSecurityService.getCurrentUser(),params), model: [projectInstanceCount: Project.countByAssignedTo(springSecurityService.getCurrentUser())]

    }


    @Secured(["ROLE_RETOUCHER"])
    def newTasks(Integer max){
        params.max = Math.min(max ?: 10, 100)
        if(!params.sort){
            params.sort = "id"
            params.order = "desc"
        }
        println("new task" + params)
        respond Project.findAllByStatus("Paid",params), model: [projectInstanceCount: Project.countByStatus("Paid")]

    }

    /*  def index(Integer max) {
          params.max = Math.min(max ?: 10, 100)
          respond Task.list(params), model: [taskInstanceCount: Task.count()]
      }*/


    @Secured(["ROLE_RETOUCHER","ROLE_ADMIN"])
    def show(Project projectInstance) {
        println(projectInstance.status)
        if(projectInstance.status == 'New'){
            redirect(action: "newTasks")
        }

        if(!projectInstance.assignedTo || projectInstance.assignedTo == springSecurityService.getCurrentUser()){
            respond projectInstance
        }else{
            flash.message = "Claim Failed! Someone else must have claimed the task before you."
            redirect(action: 'myTasks')
        }

    }

    /* def create() {
         respond new Task(params)
     }*/

    /*  @Transactional
      def save(Task taskInstance) {
          if (taskInstance == null) {
              notFound()
              return
          }

          if (taskInstance.hasErrors()) {
              respond taskInstance.errors, view: 'create'
              return
          }

          taskInstance.save flush: true

          request.withFormat {
              form multipartForm {
                  flash.message = message(code: 'default.created.message', args: [message(code: 'task.label', default: 'Task'), taskInstance.id])
                  redirect taskInstance
              }
              '*' { respond taskInstance, [status: CREATED] }
          }
      }
  */
    /*def edit(Task taskInstance) {
        respond taskInstance
    }*/

    /*  @Transactional
      def update(Task taskInstance) {
          if (taskInstance == null) {
              notFound()
              return
          }

          if (taskInstance.hasErrors()) {
              respond taskInstance.errors, view: 'edit'
              return
          }

          taskInstance.save flush: true

          request.withFormat {
              form multipartForm {
                  flash.message = message(code: 'default.updated.message', args: [message(code: 'Task.label', default: 'Task'), taskInstance.id])
                  redirect taskInstance
              }
              '*' { respond taskInstance, [status: OK] }
          }
      }*/

    /* @Transactional
     def delete(Task taskInstance) {

         if (taskInstance == null) {
             notFound()
             return
         }

         taskInstance.delete flush: true

         request.withFormat {
             form multipartForm {
                 flash.message = message(code: 'default.deleted.message', args: [message(code: 'Task.label', default: 'Task'), taskInstance.id])
                 redirect action: "index", method: "GET"
             }
             '*' { render status: NO_CONTENT }
         }
     }*/

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'task.label', default: 'Task'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/task/_form.gsp
<%@ page import="com.retouch.Task" %>



<div class="fieldcontain ${hasErrors(bean: taskInstance, field: 'finalImage', 'error')} ">
	<label for="finalImage">
		<g:message code="task.finalImage.label" default="Final Image" />
		
	</label>
	<g:select id="finalImage" name="finalImage.id" from="${com.retouch.ReImage.list()}" optionKey="id" value="${taskInstance?.finalImage?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: taskInstance, field: 'createAt', 'error')} required">
	<label for="createAt">
		<g:message code="task.createAt.label" default="Create At" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="createAt" precision="day"  value="${taskInstance?.createAt}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: taskInstance, field: 'originalImage', 'error')} required">
	<label for="originalImage">
		<g:message code="task.originalImage.label" default="Original Image" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="originalImage" name="originalImage.id" from="${com.retouch.ReImage.list()}" optionKey="id" required="" value="${taskInstance?.originalImage?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: taskInstance, field: 'project', 'error')} required">
	<label for="project">
		<g:message code="task.project.label" default="Project" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="project" name="project.id" from="${com.retouch.Project.list()}" optionKey="id" required="" value="${taskInstance?.project?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: taskInstance, field: 'tags', 'error')} ">
	<label for="tags">
		<g:message code="task.tags.label" default="Tags" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${taskInstance?.tags?}" var="t">
    <li><g:link controller="imageTag" action="show" id="${t.id}">${t?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="imageTag" action="create" params="['task.id': taskInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'imageTag.label', default: 'ImageTag')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: taskInstance, field: 'techniques', 'error')} ">
	<label for="techniques">
		<g:message code="task.techniques.label" default="Techniques" />
		
	</label>
	<g:select name="techniques" from="${com.retouch.Technique.list()}" multiple="multiple" optionKey="id" size="5" value="${taskInstance?.techniques*.id}" class="many-to-many"/>

</div>

grails-app/views/task/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'task.label', default: 'Task')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-task" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:hasErrors bean="${taskInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${taskInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:taskInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/task/edit.gsp
<%@ page import="com.retouch.Task" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'task.label', default: 'Task')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-task" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:hasErrors bean="${taskInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${taskInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:taskInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${taskInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/task/index.gsp
<%@ page import="com.retouch.Task" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName"
	value="${message(code: 'task.label', default: 'Task')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>

	<div role="main" class="main">

		<section class="page-top">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb">
							<li><a class="home" href="${createLink(uri: '/')}"><g:message
										code="default.home.label" /></a></li>
							<li><g:message code="default.list.label" args="[entityName]" /></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<h1>
							<g:message code="default.list.label" args="[entityName]" />
						</h1>
					</div>
				</div>
			</div>
		</section>

		<div class="container">
			<div class="alert alert-info">Change Text</div>

			<div class="panel-body">
				<div class="table-responsive">

					<table
						class="table table-bordered table-striped table-condensed mb-none">
						<thead>
							<tr>
								
						<th><g:message code="task.finalImage.label" default="Final Image" /></th>
					
						<g:sortableColumn property="createAt" title="${message(code: 'task.createAt.label', default: 'Create At')}" />
					
						<th><g:message code="task.originalImage.label" default="Original Image" /></th>
					
						<th><g:message code="task.project.label" default="Project" /></th>
					
							</tr>
						</thead>
						<tbody>
							<g:each in="${taskInstanceList}" status="i"
								var="taskInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
									
									<td><g:link action="show" id="${taskInstance.id}">${fieldValue(bean: taskInstance, field: "finalImage")}</g:link></td>
								
									<td><g:formatDate date="${taskInstance.createAt}" /></td>
								
									<td>${fieldValue(bean: taskInstance, field: "originalImage")}</td>
								
									<td>${fieldValue(bean: taskInstance, field: "project")}</td>
								

								</tr>
							</g:each>
						</tbody>
					</table>
					<ul class="pagination">
						<retouch:paginate total="${taskInstanceCount ?: 0}" />
					</ul>

				</div>
			</div>
			</section>
		</div>
	</div>
</body>
</html>

grails-app/views/task/myTasks.gsp
<%--
  Created by IntelliJ IDEA.
  User: Aasiz
  Date: 2/26/2015
  Time: 2:06 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'project.label', default: 'My Task')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li class="active">My Tasks</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container" id="projectFilterList">
        <div class="col-md-12">

            <div class="col-md-9 pull-right bold">
                <div class="col-md-3">
                    Project Id
                </div>
                <div class="col-md-3">
                    Date Created
                </div>
                <div class="col-md-3">
                    Last Updated
                </div>
                <div class="col-md-3">
                    Status
                </div>
            </div>

            <g:each in="${projectInstanceList}" status="i" var="projectInstance">
                <div class="col-md-12 push-top">

                    <div class="col-md-3">
                        <g:link action="show" id="${projectInstance.id}">
                            <img id="uploadedImage1" class="img-rounded img-responsive"
                                 src="${grailsApplication.config.retouch.imageServer}${projectInstance?.task?.originalImage?.getLargeImageName()}">
                        </g:link>
                    </div>

                    <br>
                    <div class="well col-md-9 center">
                        <div class="col-md-3">
                            <g:link action="show" id="${projectInstance.id}">${fieldValue(bean: projectInstance, field: "projectId")}</g:link>
                        </div>

                        <div class="col-md-3">
                            <prettytime:display date="${projectInstance.createdDate}"/>
                        </div>

                        <div class="col-md-3">
                            <prettytime:display date="${projectInstance.lastUpdated}"/>
                        </div>

                        <div class="col-md-3">
                            <span class="tag label
                            <g:if test="${projectInstance.status == 'New'}">btn-danger</g:if>
                            <g:if test="${projectInstance.status == 'Paid'}">btn-warning</g:if>
                            <g:if test="${projectInstance.status == 'In Progress'}">btn-info</g:if>
                            <g:if test="${projectInstance.status == 'In Review'}">btn-dark</g:if>
                            <g:if test="${projectInstance.status == 'Complete'}">btn-success</g:if> ">
                                ${fieldValue(bean: projectInstance, field: "status")}
                            </span>
                        </div>
                    </div>
                </div>
                <hr class="tall" />
            </g:each>
            <ul class="pagination pull-right">
                <retouch:paginate total="${projectInstanceCount ?: 0}"/>
            </ul>
        </div>
    </div>








</div>

</body>
</html>

grails-app/views/task/newTasks.gsp
<%--
  Created by IntelliJ IDEA.
  User: Aasiz
  Date: 2/26/2015
  Time: 2:06 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'project.label', default: 'Project')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<div role="main" class="main">

    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li class="active">New Tasks</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container" id="projectFilterList">
        <div class="col-md-12">

            <div class="col-md-9 pull-right bold">
                <div class="col-md-3">
                    Project Id
                </div>
                <div class="col-md-3">
                    Date Created
                </div>
                <div class="col-md-3">
                    Last Updated
                </div>
                <div class="col-md-3">
                    Status
                </div>
            </div>

            <g:each in="${projectInstanceList}" status="i" var="projectInstance">
                <div class="col-md-12 push-top">

                    <div class="col-md-3">
                        <g:link action="show" id="${projectInstance.id}">
                            <img id="uploadedImage1" class="img-rounded img-responsive"
                                 src="${grailsApplication.config.retouch.imageServer}${projectInstance?.task?.originalImage?.getLargeImageName()}">
                        </g:link>
                    </div>

                    <br>
                    <div class="well col-md-9 center">
                        <div class="col-md-3">
                            <g:link action="show" id="${projectInstance.id}">${fieldValue(bean: projectInstance, field: "projectId")}</g:link>
                        </div>

                        <div class="col-md-3">
                            <prettytime:display date="${projectInstance.createdDate}"/>
                        </div>

                        <div class="col-md-3">
                            <prettytime:display date="${projectInstance.lastUpdated}"/>
                        </div>

                        <div class="col-md-3">
                            <span class="tag label
                            <g:if test="${projectInstance.status == 'New'}">btn-danger</g:if>
                            <g:if test="${projectInstance.status == 'Paid'}">btn-warning</g:if>
                            <g:if test="${projectInstance.status == 'In Progress'}">btn-info</g:if>
                            <g:if test="${projectInstance.status == 'In Review'}">btn-dark</g:if>
                            <g:if test="${projectInstance.status == 'Complete'}">btn-success</g:if> ">
                                ${fieldValue(bean: projectInstance, field: "status")}
                            </span>
                        </div>
                    </div>
                </div>
                <hr class="tall" />
            </g:each>
            <ul class="pagination pull-right">
                <retouch:paginate total="${projectInstanceCount ?: 0}"/>
            </ul>
        </div>
    </div>

</div>

</body>
</html>